// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC16QkyUB5x9AMp795qTMoaAZHieKBQAP4',
    appId: '1:779676222833:web:74b66b335b08bc908da2d0',
    messagingSenderId: '779676222833',
    projectId: 'safehome-bcb20',
    authDomain: 'safehome-bcb20.firebaseapp.com',
    storageBucket: 'safehome-bcb20.firebasestorage.app',
    measurementId: 'G-G5W1N94963',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQdcfhdZJKiaDHuVcs77SCox06eE1O9A0',
    appId: '1:779676222833:android:13be162ccc265e2f8da2d0',
    messagingSenderId: '779676222833',
    projectId: 'safehome-bcb20',
    storageBucket: 'safehome-bcb20.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiaiFHVjP9PFxZsD0UgNMXSviKb-uidb8',
    appId: '1:779676222833:ios:66110104a6176f408da2d0',
    messagingSenderId: '779676222833',
    projectId: 'safehome-bcb20',
    storageBucket: 'safehome-bcb20.firebasestorage.app',
    iosBundleId: 'com.example.safehome',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiaiFHVjP9PFxZsD0UgNMXSviKb-uidb8',
    appId: '1:779676222833:ios:66110104a6176f408da2d0',
    messagingSenderId: '779676222833',
    projectId: 'safehome-bcb20',
    storageBucket: 'safehome-bcb20.firebasestorage.app',
    iosBundleId: 'com.example.safehome',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC16QkyUB5x9AMp795qTMoaAZHieKBQAP4',
    appId: '1:779676222833:web:a2380639303add3b8da2d0',
    messagingSenderId: '779676222833',
    projectId: 'safehome-bcb20',
    authDomain: 'safehome-bcb20.firebaseapp.com',
    storageBucket: 'safehome-bcb20.firebasestorage.app',
    measurementId: 'G-NDCBH8V4NN',
  );
}
